### Rozhuk Ivan, 2011.03-2023
### unbound.conf
### http://www.unbound.net/documentation/unbound.conf.html




#Use this to include other text into the file.
#include: "otherfile.conf"


# The server clause sets the main parameters. 
server:
...
	# the pid file. Can be an absolute path outside of chroot/work dir.
	pidfile: "/var/run/unbound.pid"

	# if given, a chroot(2) is done to the given directory.
	# i.e. you can chroot to the working directory, for example,
	# for extra security, but make sure all files are in that directory.
	#
	# If chroot is enabled, you should pass the configfile (from the
	# commandline) as a full path from the original root. After the
	# chroot has been performed the now defunct portion of the config 
	# file path is removed to be able to reread the config after a reload. 
	#
	# All other file paths (working dir, logfile, roothints, and
	# key files) can be specified in several ways:
	# 	o as an absolute path relative to the new root.
	# 	o as a relative path to the working directory.
	# 	o as an absolute path relative to the original root.
	# In the last case the path is adjusted to remove the unused portion.
	#
	# The pid file can be absolute and outside of the chroot, it is 
	# written just prior to performing the chroot and dropping permissions.
	#
	# Additionally, unbound may need to access /dev/random (for entropy).
	# How to do this is specific to your OS.
	#
	# If you give "" no chroot is performed. The path must not end in a /.
	# chroot: "/usr/local/etc/unbound"

	# if given, user privileges are dropped (after binding port),
	# and the given username is assumed. Default is user "unbound".
	# If you give "" no privileges are dropped.
	username: "unbound"

	# the working directory. The relative files in this config are 
	# relative to this directory. If you give "" the working directory
	# is not changed.
	directory: "/usr/local/etc/unbound"

	# module configuration of the server. A string with identifiers
	# separated by spaces. "iterator" or "validator iterator"
	module-config: "iterator"

	# if given, a chroot(2) is done to the given directory.
	# i.e. you can chroot to the working directory, for example,
	# for extra security, but make sure all files are in that directory.
	chroot: "/var/run/chroot-unbound"
...
