;;; Rozhuk Ivan 2014-2026
;;; FPM Configuration pool config
;;;

[www_pub_nextcloud]
...
user						= www
group						= www

listen						= /var/run/php-fcgi-www_pub_nextcloud.sock
listen.owner					= www
listen.group					= www
listen.mode					= 1777
listen.backlog					= -1
...
chroot						= /var/run/chroot-php-nextcloud/
chdir						= /tmp
...