;;; Rozhuk Ivan 2014-2026
;;; FPM Configuration pool config
;;;

[www_pub_dokuwiki]
...
user						= www
group						= www

listen						= /var/run/php-fcgi-www_pub_dokuwiki.sock
listen.owner					= www
listen.group					= www
listen.mode					= 1777
...
chroot						= /var/run/chroot-php-dokuwiki/
chdir						= /tmp
...
