#!/bin/sh
### Rozhuk Ivan 2026
### chroot config file for net/chrony
###


CHROOT_DIR='/var/run/chroot-chrony'
CHROOT_USER='ntpd'
CHROOT_MNT_ROOT_SIZE='16m'
CHROOT_MNT_MAP_RW="
/var/run
"
CHROOT_APP_CP_LIST="
/usr/local/etc/chrony.conf
"
CHROOT_APP_EXEC_LIST="
/usr/local/sbin/chronyd
"
